flowchart TD
    subgraph discover_videos_for_topic
        discover_start([Start])
        discover_0(get_topic_video_ids)
        discover_start --> discover_0
        discover_1(search_videos_by_keyword ♻)
        discover_0 -.-> discover_1
        discover_2(fetch_creator_videos ♻)
        discover_1 -.-> discover_2
        discover_end([End])
        discover_2 --> discover_end
    end
    subgraph process_video_for_topic
        process__start([Start])
        process__0(fetch_video_metadata)
        process__start --> process__0
        process__1(fetch_transcript)
        process__0 --> process__1
        process__2(save_video)
        process__1 --> process__2
        process__3(link_video_to_topic)
        process__2 --> process__3
        process__4(criterion_result_exists ♻)
        process__3 -.-> process__4
        process__5(evaluate_criterion ♻)
        process__4 -.-> process__5
        process__6(save_criterion_result ♻)
        process__5 -.-> process__6
        process__end([End])
        process__6 --> process__end
    end
    subgraph video_pipeline
        video_pi_start([Start])
        video_pi_0(get_active_topics)
        video_pi_start --> video_pi_0
        video_pi_1([discover_videos_for_topic ♻])
        video_pi_0 -.-> video_pi_1
        video_pi_2([process_video_for_topic ♻])
        video_pi_1 -.-> video_pi_2
        video_pi_end([End])
        video_pi_2 --> video_pi_end
    end
