"""
Auto-generated Pydantic models from the Prisma schema.

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with:  uv run python scripts/generate_models.py
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class IdeaGraphGenerationStatus(str, Enum):
    IDLE = "IDLE"
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class IdeaGraphLayoutDirection(str, Enum):
    LR = "LR"
    TB = "TB"


class IdeaGraphNodeType(str, Enum):
    CLAIM = "CLAIM"
    EVIDENCE = "EVIDENCE"
    COUNTERARGUMENT = "COUNTERARGUMENT"
    REBUTTAL = "REBUTTAL"
    EXAMPLE = "EXAMPLE"
    ASSUMPTION = "ASSUMPTION"
    DEFINITION = "DEFINITION"
    QUESTION = "QUESTION"
    CONCLUSION = "CONCLUSION"


class IdeaGraphEdgeType(str, Enum):
    SUPPORTS = "SUPPORTS"
    ATTACKS = "ATTACKS"
    REBUTS = "REBUTS"
    ELABORATES = "ELABORATES"
    DEPENDS_ON = "DEPENDS_ON"
    ILLUSTRATES = "ILLUSTRATES"
    CONTRASTS_WITH = "CONTRASTS_WITH"


class FunnelVideoStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PENDING_RETRY = "PENDING_RETRY"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class ClassNodeResultValue(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    CANNOT_TELL = "CANNOT_TELL"


class TrainingStatus(str, Enum):
    PENDING = "PENDING"
    TRAINING = "TRAINING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TrainingMethod(str, Enum):
    SFT = "SFT"
    RLVR = "RLVR"


class User(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    name: str | None = Field(default=None)
    email: str | None = Field(default=None)
    email_verified: datetime | None = Field(default=None, alias="emailVerified")
    image: str | None = Field(default=None)
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class Account(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    user_id: str = Field(alias="userId")
    type: str
    provider: str
    provider_account_id: str = Field(alias="providerAccountId")
    refresh_token: str | None = Field(default=None)
    access_token: str | None = Field(default=None)
    expires_at: int | None = Field(default=None)
    token_type: str | None = Field(default=None)
    scope: str | None = Field(default=None)
    id_token: str | None = Field(default=None)
    session_state: str | None = Field(default=None)


class Session(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    session_token: str = Field(alias="sessionToken")
    user_id: str = Field(alias="userId")
    expires: datetime


class VerificationToken(BaseModel):
    identifier: str
    token: str
    expires: datetime


class Video(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    title: str
    description: str
    channel_title: str = Field(alias="channelTitle")
    channel_id: str = Field(alias="channelId")
    published_at: datetime = Field(alias="publishedAt")
    view_count: int = Field(default=0, alias="viewCount")
    like_count: int = Field(default=0, alias="likeCount")
    comment_count: int = Field(default=0, alias="commentCount")
    duration_seconds: int = Field(alias="durationSeconds")
    definition: str = Field(default="hd")
    caption: str = Field(default="false")
    tags: list[str] = Field(default_factory=list)
    thumbnail_default: str | None = Field(default=None, alias="thumbnailDefault")
    thumbnail_medium: str | None = Field(default=None, alias="thumbnailMedium")
    thumbnail_high: str | None = Field(default=None, alias="thumbnailHigh")
    transcript: str | None = Field(default=None)
    summary: str | None = Field(default=None)
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class Channel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    title: str
    description: str | None = Field(default=None)
    custom_url: str | None = Field(default=None, alias="customUrl")
    thumbnail_url: str | None = Field(default=None, alias="thumbnailUrl")
    subscriber_count: int = Field(default=0, alias="subscriberCount")
    video_count: int = Field(default=0, alias="videoCount")
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class Review(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    user_id: str = Field(alias="userId")
    video_id: str = Field(alias="videoId")
    funnel_id: str | None = Field(default=None, alias="funnelId")
    rating: int
    content: str | None = Field(default=None)
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class IdeaGraph(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    user_id: str = Field(alias="userId")
    video_id: str = Field(alias="videoId")
    generation_status: IdeaGraphGenerationStatus = Field(alias="generationStatus")
    generation_error: str | None = Field(default=None, alias="generationError")
    generated_at: datetime | None = Field(default=None, alias="generatedAt")
    layout_direction: IdeaGraphLayoutDirection = Field(alias="layoutDirection")
    visible_depth: int | None = Field(default=None, alias="visibleDepth")
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class IdeaGraphNode(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    graph_id: str = Field(alias="graphId")
    type: IdeaGraphNodeType
    title: str = Field(default="")
    content: str | None = Field(default=None)
    x: float = Field(default=0)
    y: float = Field(default=0)
    collapsed: bool = Field(default=False)
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class IdeaGraphEdge(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    graph_id: str = Field(alias="graphId")
    source_node_id: str = Field(alias="sourceNodeId")
    target_node_id: str = Field(alias="targetNodeId")
    type: IdeaGraphEdgeType
    label: str | None = Field(default=None)
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class IdeaGraphNodeSource(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    node_id: str = Field(alias="nodeId")
    paraphrase: str | None = Field(default=None)
    quote: str
    start_sec: float = Field(alias="startSec")
    end_sec: float = Field(alias="endSec")
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class FunnelVideo(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    funnel_id: str = Field(alias="funnelId")
    video_id: str = Field(alias="videoId")
    status: FunnelVideoStatus
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class Funnel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    name: str
    description: str | None = Field(default=None)
    user_id: str = Field(alias="userId")
    active: bool = Field(default=True)
    pipeline_interval_hours: int = Field(default=6, alias="pipelineIntervalHours")
    last_pipeline_run_at: datetime | None = Field(default=None, alias="lastPipelineRunAt")
    max_videos_per_keyword: int = Field(default=20, alias="maxVideosPerKeyword")
    max_videos_per_creator: int = Field(default=30, alias="maxVideosPerCreator")
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class ClassNode(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    title: str = Field(default="")
    description: str | None = Field(default=None)
    parent_class_node_id: str | None = Field(default=None, alias="parentClassNodeId")
    funnel_id: str | None = Field(default=None, alias="funnelId")
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class MergeNode(BaseModel):
    pass


class GoldStandard(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    class_node_id: str = Field(alias="classNodeId")
    video_url: str = Field(alias="videoUrl")
    title: str | None = Field(default=None)
    is_positive: bool = Field(default=True, alias="isPositive")
    note: str | None = Field(default=None)
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class FunnelKeyword(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    funnel_id: str = Field(alias="funnelId")
    keyword: str
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class FunnelCreator(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    funnel_id: str = Field(alias="funnelId")
    channel_id: str | None = Field(default=None, alias="channelId")
    channel_url: str | None = Field(default=None, alias="channelUrl")
    channel_name: str | None = Field(default=None, alias="channelName")
    scrape_months_back: int = Field(default=1, alias="scrapeMonthsBack")
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class LLM(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    provider: str
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class ClassNodeResult(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    video_id: str = Field(alias="videoId")
    class_node_id: str = Field(alias="classNodeId")
    result: ClassNodeResultValue
    confidence: float
    explanation: str | None = Field(default=None)
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class ClassNodeModelVerdict(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    video_id: str = Field(alias="videoId")
    class_node_id: str = Field(alias="classNodeId")
    class_node_result_id: str = Field(alias="classNodeResultId")
    llm_id: str = Field(alias="llmId")
    rationale: str
    verdict: bool
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")


class TrainingRun(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    user_id: str = Field(alias="userId")
    funnel_id: str = Field(alias="funnelId")
    status: TrainingStatus
    method: TrainingMethod
    model_name: str = Field(alias="modelName")
    version: int
    checkpoint_path: str | None = Field(default=None, alias="checkpointPath")
    base_model: str = Field(default="meta-llama/Llama-3.1-8B-Instruct", alias="baseModel")
    config: Any | None = Field(default=None)
    metrics: Any | None = Field(default=None)
    dataset_size: int | None = Field(default=None, alias="datasetSize")
    webhook_url: str | None = Field(default=None, alias="webhookUrl")
    error: str | None = Field(default=None)
    is_active: bool = Field(default=False, alias="isActive")
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")
    completed_at: datetime | None = Field(default=None, alias="completedAt")
