"""
Generate Pydantic models from the Prisma schema file.

Parses application/prisma/schema.prisma and outputs orchestrator/models/_generated.py
so the Python models stay in sync with the database schema automatically.

Usage:
    uv run python scripts/generate_models.py
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

SCHEMA_PATH = (
    Path(__file__).resolve().parent.parent.parent
    / "application"
    / "prisma"
    / "schema.prisma"
)
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "models" / "_generated.py"

# ── Prisma type → Python type mapping ─────────────────────────

PRISMA_TYPE_MAP: dict[str, str] = {
    "String": "str",
    "Int": "int",
    "BigInt": "int",
    "Float": "float",
    "Boolean": "bool",
    "DateTime": "datetime",
    "Json": "Any",
    "Bytes": "bytes",
    "Decimal": "Decimal",
}

# @default() values that are auto-generated by the DB (not user-supplied)
AUTO_DEFAULTS = frozenset(
    {"now()", "cuid()", "uuid()", "autoincrement()", "dbgenerated()"}
)


# ── Data structures ───────────────────────────────────────────


@dataclass
class EnumDef:
    name: str
    values: list[str]


@dataclass
class FieldDef:
    name: str  # original camelCase name from Prisma
    prisma_type: str
    python_type: str
    is_optional: bool
    is_list: bool
    is_id: bool
    default_repr: str | None  # Python repr of the default value, or None
    is_auto_default: bool  # True if default is now(), cuid(), @updatedAt, etc.


@dataclass
class ModelDef:
    name: str
    fields: list[FieldDef] = field(default_factory=list)


# ── Helpers ───────────────────────────────────────────────────


def camel_to_snake(name: str) -> str:
    """Convert camelCase to snake_case."""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def _parse_default(attrs: str) -> tuple[str | None, bool]:
    """
    Extract @default(value) from a Prisma attribute string.
    Returns (python_repr_of_default, is_auto_generated).
    """
    # Handle one level of nested parens: @default(cuid()), @default(now()), etc.
    match = re.search(r"@default\(([^()]*(?:\([^)]*\))?)\)", attrs)
    if not match:
        return None, False

    value = match.group(1).strip()

    if value in AUTO_DEFAULTS:
        return None, True

    # Boolean
    if value == "true":
        return "True", False
    if value == "false":
        return "False", False

    # Quoted string
    str_match = re.match(r'^"([^"]*)"$', value)
    if str_match:
        return f'"{str_match.group(1)}"', False

    # Integer
    try:
        int(value)
        return value, False
    except ValueError:
        pass

    # Float
    try:
        float(value)
        return value, False
    except ValueError:
        pass

    return None, False


# ── Schema parser ─────────────────────────────────────────────


def parse_schema(text: str) -> tuple[list[EnumDef], list[ModelDef]]:
    """Parse a Prisma schema string into enum and model definitions."""

    # 1. Collect enums
    enums: list[EnumDef] = []
    for match in re.finditer(r"enum\s+(\w+)\s*\{([^}]*)\}", text, re.DOTALL):
        name = match.group(1)
        body = match.group(2)
        values: list[str] = []
        for raw_line in body.splitlines():
            line = raw_line.split("//", 1)[0].strip()
            if line:
                values.append(line)
        enums.append(EnumDef(name=name, values=values))

    enum_names = {e.name for e in enums}

    # 2. Collect all model names (to detect relation fields)
    model_names = set(re.findall(r"model\s+(\w+)\s*\{", text))

    # 3. Parse each model
    models: list[ModelDef] = []
    for match in re.finditer(r"model\s+(\w+)\s*\{([^}]*)\}", text, re.DOTALL):
        model_name = match.group(1)
        body = match.group(2)
        fields: list[FieldDef] = []

        for line in body.splitlines():
            line = line.strip()

            # Skip empty lines, comments, block-level attributes
            if not line or line.startswith("//") or line.startswith("@@"):
                continue

            # Parse field: fieldName TypeName[?|[]] [@attributes...]
            field_match = re.match(
                r"^(\w+)\s+(\w+)(\?|\[\])?\s*(.*)$", line
            )
            if not field_match:
                continue

            field_name = field_match.group(1)
            type_name = field_match.group(2)
            modifier = field_match.group(3) or ""
            attrs = field_match.group(4) or ""

            # Skip relation fields (type is another model)
            if type_name in model_names:
                continue

            is_optional = modifier == "?"
            is_list = modifier == "[]"
            is_id = "@id" in attrs
            is_updated_at = "@updatedAt" in attrs

            # Determine Python type
            if type_name in enum_names:
                python_type = type_name
            elif type_name in PRISMA_TYPE_MAP:
                python_type = PRISMA_TYPE_MAP[type_name]
            else:
                continue  # unknown type, skip

            # Parse @default()
            default_repr, is_auto = _parse_default(attrs)

            # Auto-generated timestamps are optional (DB sets them),
            # but auto-generated IDs stay required (always present in reads).
            is_auto_timestamp = (is_auto and not is_id) or is_updated_at

            fields.append(
                FieldDef(
                    name=field_name,
                    prisma_type=type_name,
                    python_type=python_type,
                    is_optional=is_optional,
                    is_list=is_list,
                    is_id=is_id,
                    default_repr=default_repr,
                    is_auto_default=is_auto_timestamp,
                )
            )

        models.append(ModelDef(name=model_name, fields=fields))

    return enums, models


# ── Code generator ────────────────────────────────────────────


def generate_code(enums: list[EnumDef], models: list[ModelDef]) -> str:
    """Generate Python source code with Pydantic models."""

    lines: list[str] = [
        '"""',
        "Auto-generated Pydantic models from the Prisma schema.",
        "",
        "DO NOT EDIT THIS FILE MANUALLY.",
        "Regenerate with:  uv run python scripts/generate_models.py",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from datetime import datetime",
        "from enum import Enum",
        "from typing import Any",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
    ]

    # ── Enums ──
    for enum in enums:
        lines.append("")
        lines.append(f"class {enum.name}(str, Enum):")
        for value in enum.values:
            lines.append(f'    {value} = "{value}"')
        lines.append("")

    # ── Models ──
    for model in models:
        lines.append("")
        lines.append(f"class {model.name}(BaseModel):")

        # Check if any field needs a camelCase → snake_case alias
        has_aliases = any(
            camel_to_snake(f.name) != f.name for f in model.fields
        )
        if has_aliases:
            lines.append("    model_config = ConfigDict(populate_by_name=True)")
            lines.append("")

        if not model.fields:
            lines.append("    pass")
            lines.append("")
            continue

        for f in model.fields:
            snake = camel_to_snake(f.name)
            needs_alias = snake != f.name

            # Build type annotation
            if f.is_list:
                type_str = f"list[{f.python_type}]"
            else:
                type_str = f.python_type

            is_field_optional = f.is_optional or f.is_auto_default
            if is_field_optional:
                type_str = f"{type_str} | None"

            # Build default / Field(...)
            field_kwargs: list[str] = []

            if f.is_list:
                field_kwargs.append("default_factory=list")
            elif f.default_repr is not None:
                field_kwargs.append(f"default={f.default_repr}")
            elif is_field_optional:
                field_kwargs.append("default=None")

            if needs_alias:
                field_kwargs.append(f'alias="{f.name}"')

            # Format the line
            if field_kwargs:
                kwargs_str = ", ".join(field_kwargs)
                lines.append(f"    {snake}: {type_str} = Field({kwargs_str})")
            else:
                lines.append(f"    {snake}: {type_str}")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ── Main ──────────────────────────────────────────────────────


def main() -> None:
    if not SCHEMA_PATH.exists():
        raise FileNotFoundError(f"Prisma schema not found at {SCHEMA_PATH}")

    schema_text = SCHEMA_PATH.read_text(encoding="utf-8")
    enums, models = parse_schema(schema_text)
    code = generate_code(enums, models)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(code, encoding="utf-8")

    print(f"Generated {len(enums)} enums and {len(models)} models")
    print(f"Output: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
